name: Workflow for dump aiml

on: [push]

jobs:
  aimldump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: dump aiml
        uses: ./.github/action-dump-aiml/
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: "[Workflow] dump aiml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
